### PR TITLE
Build environment Nix-ification

### PR DESCRIPTION
**Pull request by deepfire**
Tested using `make qemu_x86_64_debug` on NixOS and Debian Jessie (actually, SteamOS), both inside `nix-shell`.

This goes 95% of the way to obtain a fully reproducible build environment using [Nix/Nixpkgs](https://nixos.org/nixpkgs/) -- all that remains is:
 - a short README needs to be written, which needs inspiration
 - a policy for pinning `nixpkgs` (and hence input package versions) to a particular version

Meanwhile, if you have Nix (the package manager) installed, you can issue
 ```
nix-shell --no-build-output
```
 (or `nix-shell --pure --no-build-output`) inside the source tree, and watch Nix construct an environment for you -- on _**any**_ Linux distribution.

### CODE REVIEW

**Comment by simu** [comment]
@barrelfish-bot test this please

**Comment by simu** [comment]
@barrelfish-bot retest this please
@deepfire Please excuse the spam, our public tests are a bit rusty

**Comment by simu** [comment]
@barrelfish-bot retest this please

**Comment by simu** [comment]
@deepfire Thanks for the work!

A few comments:
1) The default compiler flags include `-fno-stack-protector` which should prohibit GCC from emitting any `__stack_chk_*()` calls.
2) In general, I'm not keen on being restricted to plain sh for writing helper scripts, I'd prefer if alternate build environments just included bash.
3) We have a cleaner solution for ghc8 support internally, as it turns out, `Opt_DeriveDataTypeable` and `Opt_StandaloneDeriving` are not actually needed and can be left out completely.
4) In general, we do not have the manpower to ensure that alternate environments will continue to work in the future, and the only officially supported environment is the latest Ubuntu LTS (16.04.1 as of writing this).

**Comment by simu** [comment]
@barrelfish-bot retest this please

**Comment by simu** [comment]
@barrelfish-bot retest this please

**Comment by simu** [comment]
@barrelfish-bot retest this please

**Comment by deepfire** [comment]
@simu:
1. I have wrestled with that quite a bit, but some versions of GCC (or some configurations thereof) simply ignore `-fno-stack-protector`, and *still* emit `__stack_chk_fail` calls.
2. I understand.. but that's the only way to make it work on NixOS *and* on Debian derivatives simultaneously:
 - `/bin/sh` is the _only_ stable absolute path (this enforces inadvertent dependencies/impurities)
 - On NixOS `/bin/sh` is bash, so it's ok, but on Debian derivatives `/bin/sh` is `dash`, which is quite restricted
3. Good to hear!
4. As I have written in the pull request, Nixification (provisions for the Nix package manager) is a general solution to reproduction of build environments -- I hope we can discuss that further.

**Comment by simu** [comment]
@barrelfish-bot retest this please

**Comment by deepfire** [comment]
@simu, while we are at it -- I have a bunch more miscellanous changes (backtrace for the kernel, some minor x86 fixes, some minor qemu-related workflow improvements, some less categorized stuf) -- how do I better submit them?

(the changes can be seen in the `local-patches` branch in my the repository)

**Comment by deepfire** [comment]
@simu, while we are at it -- I have a bunch more miscellanous changes (backtrace for the kernel, some minor x86 fixes, some minor qemu-related workflow improvements, some less categorized stuf) -- how do I better submit them?

(the changes can be seen in the `local-patches` branch in my the repository)

**Comment by deepfire** [comment]
@simu, the failure I see in the test suite output seems to be at the very top of the technology stack:
```
Running stresstest: (3000 GET razavi-master-performanceisolation.pdf)
requesting http://10.110.4.19/razavi-master-performanceisolation.pdf
HTTP request failed for 2051, (failure count 0)
Exception:  timed out
HTTP request failed for 2052, (failure count 1)
Exception:  timed out
HTTP request failed for 2053, (failure count 2)
Exception:  timed out
HTTP request failed for 3 successive times.
Giving up for 2053, (failure count 3)
Exception while running test: Traceback (most recent call last):
  File "/mnt/local/jenkins/workspace/bf-x86_64_hw_net_quick_github/nos/src/tools/harness/tests/webserver.py", line 176, in dotest
    r = func(*args)
  File "/mnt/local/jenkins/workspace/bf-x86_64_hw_net_quick_github/nos/src/tools/harness/tests/webserver.py", line 113, in getpage_stress
    c.request('GET', '/' + page)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
timeout: timed out
```
..perhaps some network configuration issue?

**Comment by simu** [comment]
@deepfire There's a few problems with our network stack, although I haven't seen that particular error previously, it's definitely not a show stopper. Also, I've forwarded your PR to the rest of our group.

**Comment by deepfire** [comment]
@simu, and regarding the rest, is there an established workflow for submission of a bunch of heterogenous changes -- should I submit them as a whole, or should I split into separate PRs?

**Comment by simu** [comment]
@deepfire If you can sort them out into "topics" that would make it somewhat easier for us to review them. As you may have noticed, GitHub is not our primary platform, so this is a learning experience for us.

**Comment by deepfire** [comment]
@simu, thank you, will do!

**Comment by simu** [comment]
After some internal discussion, we're happy to merge this PR.

However all commits need to be signed off as stated in the [Barrelfish README](https://github.com/BarrelfishOS/barrelfish/blob/master/README#L239) before we can actually merge your changes.

**Comment by deepfire** [comment]
@simu, done!

**Comment by lluki** [comment]
I just gave it a try. I was able to build and run Barrelfish inside the nix environment!

I was not able to run tests using harness (by executing tools/harness/scalebench.py -t memtest -m qemu1), since the pexpect python package is missing. There might be other python packages that are required for scalebench. From the top of my head I remember gitpython.

pexpect: https://github.com/pexpect/pexpect 
gitpython: https://github.com/gitpython-developers/GitPython

Would be nice to add those to the nix file.

Cheers,
Lukas

**Comment by deepfire** [comment]
@lluki, I have:
1. queried http://nixos.org/nixos/packages.html for `pyexpect` -- figured out the **_attribute name_** is `python27Packages.pexpect`
2. excluded the python version number, obtaining `pythonPackages.pexpect`
3. added that to  `default.nix`
4. 
```
deepfire@andromedae:~/src/barrelfish$ nix-shell --pure
warning: dumping very large path (> 256 MiB); this may run out of memory

[nix-shell:~/src/barrelfish]$ tools/harness/scalebench.py -t memtest -m qemu1
Warning: unable to guess site, using ETH... expect breakage!
Usage: scalebench.py [options] SOURCEDIR RESULTDIR

scalebench.py: error: source and results directories must be specified
```
Voila!

**Comment by simu** [comment]
Thanks again for the contribution 👍

**Pull request merged**
